[profile.default]
src = "contracts"
test = "test/invariants"
out = "out"
libs = ["lib"]
via_ir = true
fs_permissions = [{ access = "read-write", path = "./" }]

[profile.sandbox]
src = "sandbox/contracts"
test = "test"
out = "out"
libs = ["lib"]
evm_version = "cancun"
fs_permissions = [{ access = "read-write", path = "./" }]
